version: '3'

services:
  app:
    image: node:20.1
    working_dir: /app
    command: yarn dev
    volumes:
      - .:/app
    ports:
      - 3000:3000

  storybook:
    image: node:20.1.0
    working_dir: /app
    command: yarn storybook
    volumes:
      - .:/app
    ports:
      - 6006:6006

  playwright:
    build: playwright
    command: yarn test
    volumes:
      - ./playwright:/playwright
    depends_on:
      - app
    profiles:
      - extra
