version: '3'

services:
  app:
    image: node:16
    working_dir: /app
    command: yarn dev
    volumes:
      - .:/app
    ports:
      - 3000:3000

  e2e:
    build: e2e
    volumes:
      - ./e2e:/e2e
    environment:
      - TARGET_URL=http://gateway.docker.internal:3000
    depends_on:
      - app
