version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 6006:6006

  # storybook:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   command: yarn storybook
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 6006:6006

  # playwright:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   command: yarn test:playwright
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - app
  #   profiles:
  #     - extra
