version: '3'

services:
  app:
    image: node:16
    working_dir: /app
    command: yarn dev
    volumes:
      - .:/app
    ports:
      - 3000:3000

  playwright:
    build: playwright
    volumes:
      - ./playwright:/playwright
    environment:
      - TARGET_URL=http://gateway.docker.internal:3000
    depends_on:
      - app
    profiles:
      - extra
