name: 'プルリクエストでLintとE2E'
on:
  pull_request:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20.1.0
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: biome (linter and formatter)
        run: pnpm biome:check

      - name: typescript
        run: pnpm type:check

      - name: prepare component tests
        run: pnpm storybook &
  
      - name: prepare component and E2E tests (install playwright)
        run: |
          pnpm playwright install
          pnpm playwright install-deps

      - name: component tests
        run: |
          pnpx wait-on tcp:6006
          pnpm test:storybook --url http://localhost:6006

      - name: prepare E2E tests (start next app)
        run: |
          pnpm build
          pnpm start &
        env:
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: E2E test
        run: pnpm test:playwright

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 1

      - name: notify success to slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            Success
            https://github.com/${{ github.repository }}/pull/${{ github.event.number }}

      - name: notify failure to slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            Failure
            https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
