name: 'プルリクエストでLintとE2E'
on:
  pull_request:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.1.0

      - uses: actions/cache@v4
        id: cache_node_modules
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}

      - run: yarn --frozen-lockfile
        if: steps.cache_node_modules.outputs.cache-hit != true

      - name: biome (linter and formatter)
        run: yarn biome:check

      - name: typescript
        run: yarn type:check

      - name: prepare component tests
        run: yarn storybook &
  
      - name: prepare component and E2E tests (install playwright)
        run: |
          yarn playwright install
          yarn playwright install-deps

      - name: component tests
        run: |
          npx wait-on tcp:6006
          yarn test:storybook --url http://localhost:6006

      - name: prepare E2E tests (start next app)
        run: |
          yarn build
          yarn start &
        env:
          NEXT_PUBLIC_BASE_URL: http://localhost:3000

      - name: E2E test
        run: yarn test:playwright

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 1

      - name: notify success to slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            Success
            https://github.com/${{ github.repository }}/pull/${{ github.event.number }}

      - name: notify failure to slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            Failure
            https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
